### ISSUE TITLE
Ceres has removed LocalParameterization.

### ISSUE THREAD

**Issue by l0kol** [Jmeyer1292/robot_cal_tools#111]
Hello.

I'm in the process of building your package and I noticed that if I install the latest Ceres version I get error at LocalParameterization lines. I checked the Ceres docs and it says: [LocalParameterization has been removed, use Manifold instead.](http://ceres-solver.org/version_history.html).

So maybe Ceres version should be specified in the readme before the code is updated with Manifold. Or maybe I just didn't see it, I apologize in that case for writing all this :). 

Best regards

**Comment by marip8** [comment]
See #115 for a fix. Also see [this comment](https://github.com/Jmeyer1292/robot_cal_tools/pull/115#issuecomment-2378090213) about alternatively using an improved version of `industrial_calibration` where this has already been addressed.

**Comment by l0kol** [comment]
Ah okay I see. Thank you for your answer.
