### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by cedrusx** [Jmeyer1292/robot_cal_tools#67]
Hi, this is really great work. We tried out with many calibration tools when we were calibrating our multi-sensor robot for the [OpenLORIS-Scene dataset](https://lifelong-robotic-vision.github.io/dataset/scene), and found this package the best for mocap-camera calibration in terms of both accuracy and ease of use. Thank you!

I noticed that you choose the Apache 2.0 license for all components as stated in their package.xml, which is great. How about adding a LICENSE file (e.g. copy from [here](https://github.com/moby/moby/blob/master/LICENSE)) into the root folder of the repo to make it clearer for users who care about license and more friendly for automatic IP scan tools?

**Comment by schornakj** [comment]
That's definitely a good thing to do. The other projects we maintain follow a similar pattern.

Could you submit this addition as a pull request?

**Comment by cedrusx** [comment]
Thanks @schornakj. I just created a pull request #68

**Comment by schornakj** [comment]
@marip8 @cedrusx #68 was merged in, so we can close this issue as resolved.
