### ISSUE TITLE
DH Calibration Question: Is it possible to fix certain dh parameters?

### ISSUE THREAD

**Issue by Levi-Armstrong** [Jmeyer1292/robot_cal_tools#98]
@marip8 Is it possible to fix all dh parameters except theta parameter for each joint?

**Comment by marip8** [comment]
Yes, there is a `mask` parameter in the problem where you can specify which values get optimized

https://github.com/Jmeyer1292/robot_cal_tools/blob/2fd5b85de098fc2e97d06d51addd638304e0610e/rct_optimizations/include/rct_optimizations/dh_chain_kinematic_calibration.h#L57-L67

and a helper function for creating the mask vector from an `Eigen` matrix of booleans that is the same shape as the DH parameters:

https://github.com/Jmeyer1292/robot_cal_tools/blob/2fd5b85de098fc2e97d06d51addd638304e0610e/rct_optimizations/include/rct_optimizations/dh_chain_kinematic_calibration.h#L10-L16

**Comment by marip8** [comment]
Closing; addressed by comment above and the labels were fixed by #99
